### 1. Numpy:

#### 1. list to array:

In [3]:
list_test = [3,4,6,1]

import numpy as np
np.array(list_test)

array([3, 4, 6, 1])

In [4]:
arr = np.array(list_test)
print(arr)

[3 4 6 1]


#### 2. list to 2d matrix array

In [8]:
lists_test = [[3,4,5,2],[3,7,9,2],[1,8,2,8]] #2 [[]]: matrix array
np.array(lists_test)

array([[3, 4, 5, 2],
       [3, 7, 9, 2],
       [1, 8, 2, 8]])

#### 3. create an array in a range:

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2) #np.arange(start,stop,step)

array([0, 2, 4, 6, 8])

#### 4. Generate 0, 1, eye arrays:

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones((3,4)) # 2 (()): matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(5) # Diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 5. interval points-linspace():

In [19]:
'''Return evenly spaced numbers over a specified interval.'''
np.linspace(1,11,13) #start, stop, number of points

array([ 1.        ,  1.83333333,  2.66666667,  3.5       ,  4.33333333,
        5.16666667,  6.        ,  6.83333333,  7.66666667,  8.5       ,
        9.33333333, 10.16666667, 11.        ])

#### 6. Random:

In [20]:
np.random.rand(5)

array([0.66977275, 0.4284066 , 0.86367629, 0.17116067, 0.1800326 ])

In [22]:
np.random.rand(3,4)

array([[0.04001651, 0.35729871, 0.23237308, 0.18641871],
       [0.22172974, 0.03176203, 0.87831458, 0.5556989 ],
       [0.37981476, 0.35868722, 0.2808101 , 0.73127441]])

#### 7. Random numbers in normal distribution:

In [23]:
np.random.randn(6) #Generate numbers in normal distribution

array([ 1.76648066,  0.60061563,  0.47678684,  1.36457845,  1.20165002,
       -1.76647964])

In [25]:
np.random.rand(6,2) #Row, columns

array([[0.3760854 , 0.7167056 ],
       [0.8079068 , 0.65717048],
       [0.44138042, 0.25727372],
       [0.4330008 , 0.9771398 ],
       [0.33612305, 0.25570641],
       [0.07685237, 0.05539498]])

#### 8. Generate some int betwen the range:



In [28]:
np.random.randint(1,100)

9

In [29]:
np.random.randint(1,100,10)

array([22, 38, 95, 14, 57, 83, 38,  8,  3, 66])

#### 9. Reshape

In [30]:
arr = np.random.randint(1,100,10)
arr.reshape(2,5)

array([[26, 55, 80, 81, 43],
       [39, 76, 82,  7, 40]])

In [31]:
arr.reshape(3,3) #ERROR: cannot reshape array of size 10 into shape (3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

#### 10. max()/min() & index:


In [38]:
arr = arr.reshape(2,5)
print(arr)

[[26 55 80 81 43]
 [39 76 82  7 40]]


In [33]:
print(arr.max())
print(arr.min())

82
7


In [34]:
print(arr.argmax()) #index of max
print(arr.argmin()) #index of min

7
8


#### *11. import and use some function:

In [35]:
from numpy.random import randint

In [36]:
randint(1,10,2)

array([7, 7])

### 2. Indexing & Selection:

#### 2.1 slicing:

In [41]:
arr = np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [42]:
arr1 = arr[0:5] #end is exclusives
print(arr1)

[0 1 2 3 4]


In [44]:
arr2 = arr[5:] # inclusive
print(arr2)

[ 5  6  7  8  9 10]


In [46]:
arr3 = arr[5:23]
print(arr3)

[ 5  6  7  8  9 10]


#### 2.2 Assign a slice:

In [47]:
arr[4:8] = 100
print(arr)

[  0   1   2   3 100 100 100 100   8   9  10]


In [48]:
#Compare with original:
print(arr)

[  0   1   2   3 100 100 100 100   8   9  10]


#### 2.3 Copy and assign

In [50]:
arr_copy = arr.copy()
arr_copy[4:8] = 99
print("Copy:{}".format(arr_copy))
print("Original:{}".format(arr))
'''Copy and assigning will not change the original array.'''

Copy:[ 0  1  2  3 99 99 99 99  8  9 10]
Original:[  0   1   2   3 100 100 100 100   8   9  10]


#### 2.4 Slicing:

In [6]:
import numpy as np
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [8]:
# Need [[13,14],[23,24]]
arr_slice = arr[1:3, 3:5]
arr_slice

array([[13, 14],
       [23, 24]])

#### 2.5 Conditioning:

In [10]:
bool_arr = arr>5

In [11]:
bool_arr

array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [12]:
arr[bool_arr] #Get the matrix concluding the elements>5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### OR:

In [13]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### 2.6 numpy operation:

In [14]:
arr + arr

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [15]:
arr - arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
arr*arr

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401]])

In [18]:
arr + 100

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]])

In [21]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
        5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ],
       [6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
        6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ]])

In [22]:
np.max(arr)

49

In [23]:
np.min(arr)

0

In [24]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
         0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
        -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
         0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265]])

In [25]:
np.log(arr)

C:\Anaconda3\Anaconda3_2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
        2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583],
       [3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
        3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165],
       [3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
        3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ]])

### 3. Series:
#### A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). 
#### What differentiates the NumPy array from a Series, is that a Series can have axis labels, 
#### meaning it can be indexed by a label, instead of just a number location.
#### It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

In [26]:
import pandas as pd

labels = ['a','b','c']
my_lists = [10, 20, 30]
arr = np.array(my_lists)
d = {'a':10, 'b':20, 'c':30}

#### 3.1 List to Series:

In [28]:
pd.Series(my_lists) #OR: pd.Series(data = my_lists)

0    10
1    20
2    30
dtype: int64

In [29]:
# Add labels:
pd.Series(data = my_lists, index = labels)

a    10
b    20
c    30
dtype: int64

#### 3.2 numpy.array to Series:

In [30]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [31]:
# Add labels:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

#### 3.3 Dictionary to Series:

In [32]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

#### 3.4 Using index:

#### The key to using a Series is understanding its index. 
#### Pandas makes use of these index names or numbers by allowing for fast look ups of information 
#### (works like a hash table or dictionary).

In [35]:
ser1 = pd.Series(data = [1,2,3,4], index = ['USA','Japan','China','Korea'])
ser2 = pd.Series(data = [4,9,7,2], index = ['Russia','Japan','China','USA'])

In [36]:
ser1

USA      1
Japan    2
China    3
Korea    4
dtype: int64

In [37]:
ser2

Russia    4
Japan     9
China     7
USA       2
dtype: int64

In [38]:
# Sum:
ser1 + ser2

China     10.0
Japan     11.0
Korea      NaN
Russia     NaN
USA        3.0
dtype: float64

In [39]:
ser2[0] #Russia

4

### 4. Dataframes
#### DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index.

#### 4.1 Create df & check type:

In [8]:
import pandas as pd
import numpy as np
from numpy.random import rand, randn

In [19]:
df = pd.DataFrame(randn(4,5),['R1','R2','R3','R4'],['C1','C2','C3','C4','C5']) #pd.DataFrame(data = X,X,X, index = {X,X,X})
df

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R2  0.380906  0.344015 -0.607492  0.211997 -0.394956
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

In [20]:
print(df['C1'])
print(type(df))

R1    0.195027
R2    0.380906
R3   -0.738742
R4    1.117998
Name: C1, dtype: float64
<class 'pandas.core.frame.DataFrame'>


In [21]:
df['R1'] #ERROR: could not call one row by this way.

KeyError: 'R1'

In [83]:
# Another way to create a df: Transfer dictionary to df.
d={'col1':[1,2],'col2':[3,4], 'col3':[4,]}

In [84]:
print(type(d))

<class 'dict'>


In [85]:
#Transfer dictionary to df:
df2 = pd.DataFrame(data = d, index=['r1','r2'])
df2

col1  col2  col3
r1     1     3     4
r2     2     4     4

#### 4.2 Select a sub-df by columns:

In [24]:
df[['C1','C2']]

C1        C2
R1  0.195027  0.612039
R2  0.380906  0.344015
R3 -0.738742 -1.064982
R4  1.117998 -0.830743

In [25]:
df[['R1','R2']] #ERROR: Could not call rows set by this way

KeyError: "['R1' 'R2'] not in index"

In [27]:
print(df['C2'])
print(type(df['C2'])) #<class 'pandas.core.series.Series'>

R1    0.612039
R2    0.344015
R3   -1.064982
R4   -0.830743
Name: C2, dtype: float64
<class 'pandas.core.series.Series'>


#### 4.3 Creat new column:

In [28]:
df['new'] = df['C1']+df['C2']
df

C1        C2        C3        C4        C5       new
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200  0.807066
R2  0.380906  0.344015 -0.607492  0.211997 -0.394956  0.724921
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199 -1.803724
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943  0.287254

In [35]:
# Drop one column
df.drop('new')
'''Drop one column in df, have to assign the axis=1'''

KeyError: "['new'] not found in axis"

#### 4.4 Drop column(s).

In [36]:
df.drop('new', axis=1) #axis=1 is REQUIRED when drop column.

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R2  0.380906  0.344015 -0.607492  0.211997 -0.394956
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

In [37]:
df 
'''Without inplace=True, the real df will keep the column dropped.'''

C1        C2        C3        C4        C5       new
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200  0.807066
R2  0.380906  0.344015 -0.607492  0.211997 -0.394956  0.724921
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199 -1.803724
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943  0.287254

In [38]:
# If want to delete/drop the column permentantly, have to add argument'inplace=True'.
df.drop('new', axis = 1, inplace = True)

In [39]:
df

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R2  0.380906  0.344015 -0.607492  0.211997 -0.394956
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

#### 4.5 Drop one row(s)

In [40]:
df.drop('R2', axis=0) # axis defaultly is 0 when drop one row, so it is optional to have here.

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

In [41]:
df
# If want to delete/drop the row permentantly, have to add argument'inplace=True'.

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R2  0.380906  0.344015 -0.607492  0.211997 -0.394956
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

In [42]:
df.drop('R2', axis = 0, inplace = True)
df

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

#### 4.5 Select rows by index('string'):

In [54]:
df.loc[['R1']] #By string index

#print(type(df.loc[['R1']])) #<class 'pandas.core.frame.DataFrame'>

C1        C2        C3        C4      C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.4282

In [52]:
df.loc['R1']

#print(type(df.loc['R1'])) # <class 'pandas.core.series.Series'>

C1    0.195027
C2    0.612039
C3   -0.644392
C4   -0.082517
C5    0.428200
Name: R1, dtype: float64

In [55]:
df.loc[['C3']] #ERROR: the label [C3] is not in the [index]
'''Could not select column.'''

KeyError: "None of [['C3']] are in the [index]"

In [56]:
df

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

In [57]:
df.loc[['R1','R3']] # double brackets if a df needed! Demand a multi-dimension of df.

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199

In [65]:
df.loc['R1','C3']  # locate one cell: <class 'numpy.float64'>

-0.6443920043374478

In [66]:
df

C1        C2        C3        C4        C5
R1  0.195027  0.612039 -0.644392 -0.082517  0.428200
R3 -0.738742 -1.064982 -1.198575  0.149690 -1.453199
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

In [73]:
df.loc[['R1','R4'],['C1','C3']] 
'''1. df.loc[[ROW(s)],[COL(s)]]
   2. NOT return a range, just the specified column(s).'''

C1        C3
R1  0.195027 -0.644392
R4  1.117998 -0.677479

#### 4.6 Select rows by index('int')--iloc():

In [74]:
df.iloc[2]

C1    1.117998
C2   -0.830743
C3   -0.677479
C4   -0.024851
C5    0.681943
Name: R4, dtype: float64

In [64]:
df.iloc[[2]]

C1        C2        C3        C4        C5
R4  1.117998 -0.830743 -0.677479 -0.024851  0.681943

In [75]:
df.iloc['R4'] #ERROR: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [R4] of <class 'str'>
'''df.iloc[] is just for locating by int index.'''

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [R4] of <class 'str'>

### 5. More about Dataframe:

#### 5.1 condition selection:

In [90]:
df2 = pd.DataFrame(rand(4,5),['R1','R2','R3','R4'],['C1','C2','C3','C5','C5'])

In [91]:
df2

C1        C2        C3        C5        C5
R1  0.584467  0.038737  0.700705  0.419586  0.596513
R2  0.175841  0.254650  0.610256  0.754813  0.329869
R3  0.965705  0.970872  0.974497  0.378255  0.303019
R4  0.938066  0.939298  0.345707  0.363974  0.749859

In [97]:
df2<0.5

C1     C2     C3     C5     C5
R1  False   True  False   True  False
R2   True   True  False  False   True
R3  False  False  False   True   True
R4  False  False   True   True  False

In [98]:
df2[df2<0.5] # Filter the value<0.5

C1        C2        C3        C5        C5
R1       NaN  0.038737       NaN  0.419586       NaN
R2  0.175841  0.254650       NaN       NaN  0.329869
R3       NaN       NaN       NaN  0.378255  0.303019
R4       NaN       NaN  0.345707  0.363974       NaN

In [100]:
df2['C1']<0.5

R1    False
R2     True
R3    False
R4    False
Name: C1, dtype: bool

In [101]:
df2[df2['C1']<0.5]

C1       C2        C3        C5        C5
R2  0.175841  0.25465  0.610256  0.754813  0.329869

In [104]:
df2.loc['R2']<0.5

C1     True
C2     True
C3    False
C5    False
C5     True
Name: R2, dtype: bool

In [108]:
df2[df2['C1']>0.5]['C2']

R1    0.038737
R3    0.970872
R4    0.939298
Name: C2, dtype: float64

In [111]:
df2[df2['C1']>0.5][['C2','C5']] #!!! double [[]]

C2        C5        C5
R1  0.038737  0.419586  0.596513
R3  0.970872  0.378255  0.303019
R4  0.939298  0.363974  0.749859

In [113]:
df2[df2['C1','C3']>0.5][['C2','C5']]

KeyError: ('C1', 'C3')

In [114]:
df2[(df2['C1']>0.5) & (df2['C3']>0.5)][['C2','C5']] 
# AND: doesn't work in pandas, it must be &! AND here could only be used in Bool comparation.

C2        C5        C5
R1  0.038737  0.419586  0.596513
R3  0.970872  0.378255  0.303019

In [115]:
df2[(df2['C1']>0.5) | (df2['C3']>0.5)][['C2','C5']] 
# OR:  doesn't work in pandas, it must be |. AND here could only be used in Bool comparation.

C2        C5        C5
R1  0.038737  0.419586  0.596513
R2  0.254650  0.754813  0.329869
R3  0.970872  0.378255  0.303019
R4  0.939298  0.363974  0.749859

#### 5.2:Reset Index, set_index

In [116]:
# Reset index:
df2

C1        C2        C3        C5        C5
R1  0.584467  0.038737  0.700705  0.419586  0.596513
R2  0.175841  0.254650  0.610256  0.754813  0.329869
R3  0.965705  0.970872  0.974497  0.378255  0.303019
R4  0.938066  0.939298  0.345707  0.363974  0.749859

In [117]:
df2.reset_index()
df2

C1        C2        C3        C5        C5
R1  0.584467  0.038737  0.700705  0.419586  0.596513
R2  0.175841  0.254650  0.610256  0.754813  0.329869
R3  0.965705  0.970872  0.974497  0.378255  0.303019
R4  0.938066  0.939298  0.345707  0.363974  0.749859

In [118]:
df2.reset_index(inplace = True) #inplace = True! then the index will be reseted really!
df2

index        C1        C2        C3        C5        C5
0    R1  0.584467  0.038737  0.700705  0.419586  0.596513
1    R2  0.175841  0.254650  0.610256  0.754813  0.329869
2    R3  0.965705  0.970872  0.974497  0.378255  0.303019
3    R4  0.938066  0.939298  0.345707  0.363974  0.749859

In [122]:
# Set index:
list_index = 'USA CAN CHN MOX'.split()
df2['Country'] = list_index
df2

index        C1        C2        C3        C5        C5 Country
0    R1  0.584467  0.038737  0.700705  0.419586  0.596513     USA
1    R2  0.175841  0.254650  0.610256  0.754813  0.329869     CAN
2    R3  0.965705  0.970872  0.974497  0.378255  0.303019     CHN
3    R4  0.938066  0.939298  0.345707  0.363974  0.749859     MOX

In [123]:
# Set index as Country:
df2.set_index('Country') #df2 didn't change!
df2

index        C1        C2        C3        C5        C5 Country
0    R1  0.584467  0.038737  0.700705  0.419586  0.596513     USA
1    R2  0.175841  0.254650  0.610256  0.754813  0.329869     CAN
2    R3  0.965705  0.970872  0.974497  0.378255  0.303019     CHN
3    R4  0.938066  0.939298  0.345707  0.363974  0.749859     MOX

In [125]:
df2.set_index('Country', inplace = True) 
df2
 #inplace = True! then the index will be reseted really!

index        C1        C2        C3        C5        C5
Country                                                        
USA        R1  0.584467  0.038737  0.700705  0.419586  0.596513
CAN        R2  0.175841  0.254650  0.610256  0.754813  0.329869
CHN        R3  0.965705  0.970872  0.974497  0.378255  0.303019
MOX        R4  0.938066  0.939298  0.345707  0.363974  0.749859

In [130]:
df2.loc['USA','C1']

0.5844671918582738

In [137]:
df2[['C1','C5']]

C1        C5        C5
Country                              
USA      0.584467  0.419586  0.596513
CAN      0.175841  0.754813  0.329869
CHN      0.965705  0.378255  0.303019
MOX      0.938066  0.363974  0.749859

KeyError: "['USA'] not in index"

In [139]:
df2.loc['USA','C3']

0.7007046145556456

#### 5.3 Multi-Index and Index Hierarchy:

In [166]:
import numpy as np
import pandas as pd
from numpy.random import randn

outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [167]:
hier_index = pd.MultiIndex.from_tuples(hier_index) 
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [169]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['C1','C2'])
df

C1        C2
G1 1 -1.273504  0.689416
   2 -1.831947 -0.371506
   3  2.049965 -0.163056
G2 1 -0.152416 -1.883978
   2 -0.519319  0.900969
   3  0.738600 -1.302579

#### 5.4 Locate:

In [173]:
df.loc['G1'].iloc[1] #G1-->1

C1   -1.831947
C2   -0.371506
Name: 2, dtype: float64

In [171]:
#OR:
df.loc['G1',1]

C1   -1.273504
C2    0.689416
Name: (G1, 1), dtype: float64

In [172]:
# Get the cross of line & column:
df.loc['G2'].loc[2]['C2']

0.9009687250067928

#### 5.5 Re-name the index(indice):

In [174]:
df.index.names = ['Group','Num']
df

C1        C2
Group Num                    
G1    1   -1.273504  0.689416
      2   -1.831947 -0.371506
      3    2.049965 -0.163056
G2    1   -0.152416 -1.883978
      2   -0.519319  0.900969
      3    0.738600 -1.302579

##### 5.6 Cross selection:

In [183]:
#Get all nums of Num = 1:
df.xs(2,level='Num')

C1        C2
Group                    
G1    -1.831947 -0.371506
G2    -0.519319  0.900969

In [181]:
df.xs('G1', level = 'Group')

C1        C2
Num                    
1   -1.273504  0.689416
2   -1.831947 -0.371506
3    2.049965 -0.163056

#### 5.7: Handle Missing values:

In [199]:
dict = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
dict

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [200]:
df = pd.DataFrame(dict)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [190]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [191]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [193]:
df.dropna(axis = 1) #Drop based on y/columns.

C
0  1
1  2
2  3

In [194]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [195]:
#fillna():
df.fillna(value = 'Filled')

A       B  C
0       1       5  1
1       2  Filled  2
2  Filled  Filled  3

In [196]:
df.fillna(value = df['A'].mean()) #Fill by mean of 1 column

A    B  C
0  1.0  5.0  1
1  2.0  1.5  2
2  1.5  1.5  3

### 6. Groupby on Dataframe:

In [204]:
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350],
        'Revenue':[100,50,200,100,80,200]}

In [212]:
df = pd.DataFrame(data)
df.groupby('Company')


In [214]:
by_comp = df.groupby("Company")
by_comp

In [215]:
by_comp.mean()

Sales  Revenue
Company                
FB       296.5    140.0
GOOG     160.0     75.0
MSFT     232.0    150.0

In [216]:
by_comp.sum().loc['FB']

Sales      593
Revenue    280
Name: FB, dtype: int64

In [217]:
by_comp.std()

Sales    Revenue
Company                       
FB        75.660426  84.852814
GOOG      56.568542  35.355339
MSFT     152.735065  70.710678

In [218]:
by_comp.count()

Person  Sales  Revenue
Company                        
FB            2      2        2
GOOG          2      2        2
MSFT          2      2        2

In [219]:
by_comp.max()

Person  Sales  Revenue
Company                         
FB         Sarah    350      200
GOOG         Sam    200      100
MSFT     Vanessa    340      200

In [235]:
by_comp.min()

Person  Sales  Revenue
Company                         
FB          Carl    243       80
GOOG     Charlie    120       50
MSFT         Amy    124      100

In [234]:
by_comp.min().loc['FB']

Person     Carl
Sales       243
Revenue      80
Name: FB, dtype: object

In [231]:
by_comp['Sales'].min()

Company
FB      243
GOOG    120
MSFT    124
Name: Sales, dtype: int64

In [232]:
by_comp.describe()

Revenue                                                      Sales  \
          count   mean        std    min    25%    50%    75%    max count   
Company                                                                      
FB          2.0  140.0  84.852814   80.0  110.0  140.0  170.0  200.0   2.0   
GOOG        2.0   75.0  35.355339   50.0   62.5   75.0   87.5  100.0   2.0   
MSFT        2.0  150.0  70.710678  100.0  125.0  150.0  175.0  200.0   2.0   

                                                                 
          mean         std    min     25%    50%     75%    max  
Company                                                          
FB       296.5   75.660426  243.0  269.75  296.5  323.25  350.0  
GOOG     160.0   56.568542  120.0  140.00  160.0  180.00  200.0  
MSFT     232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [233]:
by_comp.describe().transpose()

Company                FB        GOOG        MSFT
Revenue count    2.000000    2.000000    2.000000
        mean   140.000000   75.000000  150.000000
        std     84.852814   35.355339   70.710678
        min     80.000000   50.000000  100.000000
        25%    110.000000   62.500000  125.000000
        50%    140.000000   75.000000  150.000000
        75%    170.000000   87.500000  175.000000
        max    200.000000  100.000000  200.000000
Sales   count    2.000000    2.000000    2.000000
        mean   296.500000  160.000000  232.000000
        std     75.660426   56.568542  152.735065
        min    243.000000  120.000000  124.000000
        25%    269.750000  140.000000  178.000000
        50%    296.500000  160.000000  232.000000
        75%    323.250000  180.000000  286.000000
        max    350.000000  200.000000  340.000000

### 7. Merge, Join, Concatenate:

#### 7.1 Concate:
##### Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use **pd.concat** and pass in a list of DataFrames to concatenate together:

In [243]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'], 'B':['B0','B1','B2','B3'], 'C':['C0','C1','C2','C3']}, index = [0,1,2,3])
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'], 'B':['B4','B5','B6','B7'], 'C':['C4','C5','C6','C7']}, index = [4,5,6,7])
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'], 'B':['B8','B9','B10','B11'], 'C':['C8','C9','C10','C11']}, index = [8,9,10,11])

In [244]:
df1

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [245]:
df2

A   B   C
4  A4  B4  C4
5  A5  B5  C5
6  A6  B6  C6
7  A7  B7  C7

In [246]:
df3

A    B    C
8    A8   B8   C8
9    A9   B9   C9
10  A10  B10  C10
11  A11  B11  C11

In [241]:
pd.concat([df1, df2, df3]) #Default axis = 0

A    B    C
0    A0   B0   C0
1    A1   B1   C1
2    A2   B2   C2
3    A3   B3   C3
4    A4   B4   C4
5    A5   B5   C5
6    A6   B6   C6
7    A7   B7   C7
8    A8   B8   C8
9    A9   B9   C9
10  A10  B10  C10
11  A11  B11  C11

In [242]:
pd.concat([df1, df2, df3], axis=1) #concatenate along the horizontal line.

A    B    C    A    B    C    A    B    C
0    A0   B0   C0  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN   A4   B4   C4  NaN  NaN  NaN
5   NaN  NaN  NaN   A5   B5   C5  NaN  NaN  NaN
6   NaN  NaN  NaN   A6   B6   C6  NaN  NaN  NaN
7   NaN  NaN  NaN   A7   B7   C7  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8
9   NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9
10  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10
11  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11

#### 7.2 Merge:

In [319]:
left = pd.DataFrame({'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3'],'key1': ['K0', 'K0', 'K1', 'K2'], 'key2':['K0', 'K1', 'K0', 'K1']})
right = pd.DataFrame({'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3'],'key1': ['K0', 'K0', 'K1', 'K2'], 'key2': ['K0', 'K0', 'K0', 'K0']})

In [315]:
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [316]:
right

C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K0   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [295]:
pd.merge(left, right, how='inner', on='key1')

A   B key1 key2_x   C   D key2_y
0  A0  B0   K0     K0  C0  D0     K0
1  A0  B0   K0     K0  C1  D1     K0
2  A1  B1   K0     K1  C0  D0     K0
3  A1  B1   K0     K1  C1  D1     K0
4  A2  B2   K1     K0  C2  D2     K0
5  A3  B3   K2     K1  C3  D3     K0

In [305]:
pd.merge(left, right, on=['key1', 'key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A0  B0   K0   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

### 8. Joining
Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.
Join & Merge: basically the same, just the syntax is different

In [347]:
left = pd.DataFrame({'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3'],'key1':[0,1,2,3]})
right = pd.DataFrame({'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3'],'key1':[0,1,2,8]})
#ERROR: columns overlap but no suffix specified: Index(['key1'], dtype='object')

In [348]:
left

A   B  key1
0  A0  B0     0
1  A1  B1     1
2  A2  B2     2
3  A3  B3     3

In [349]:
right

C   D  key1
0  C0  D0     0
1  C1  D1     1
2  C2  D2     2
3  C3  D3     8

In [350]:
left.join(right, how='inner')
# ERROR: columns overlap but no suffix specified: Index(['key1'], dtype='object')

ValueError: columns overlap but no suffix specified: Index(['key1'], dtype='object')

In [351]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']}) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']})

In [324]:
left

A   B
0  A0  B0
1  A1  B1
2  A2  B2

In [325]:
right

C   D
0  C0  D0
1  C2  D2
2  C3  D3

In [326]:
left.join(right, how='inner')

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C2  D2
2  A2  B2  C3  D3

### 9. Other operations:


#### 9.1 Get Columns:

In [352]:
left.columns

Index(['A', 'B'], dtype='object')

In [353]:
right.index

RangeIndex(start=0, stop=3, step=1)

#### 9.2 Check if null values.

In [354]:
left.isnull() #Check if any null values.

A      B
0  False  False
1  False  False
2  False  False

In [356]:
dict = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df = pd.DataFrame(dict)
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

#### 9.3 Sort values by column(s):

In [357]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350],
        'Revenue':[100,50,200,100,80,200]}
df = pd.DataFrame(data)

In [358]:
df

Company   Person  Sales  Revenue
0    GOOG      Sam    200      100
1    GOOG  Charlie    120       50
2    MSFT      Amy    340      200
3    MSFT  Vanessa    124      100
4      FB     Carl    243       80
5      FB    Sarah    350      200

In [359]:
df.sort_values('Sales') #OR df.sort_values(by = 'Sales')

Company   Person  Sales  Revenue
1    GOOG  Charlie    120       50
3    MSFT  Vanessa    124      100
0    GOOG      Sam    200      100
4      FB     Carl    243       80
2    MSFT      Amy    340      200
5      FB    Sarah    350      200

In [365]:
df.pivot_table(values = 'Sales', index=['Company','Person'], columns = ['Revenue'])

Revenue            50     80     100    200
Company Person                             
FB      Carl       NaN  243.0    NaN    NaN
        Sarah      NaN    NaN    NaN  350.0
GOOG    Charlie  120.0    NaN    NaN    NaN
        Sam        NaN    NaN  200.0    NaN
MSFT    Amy        NaN    NaN    NaN  340.0
        Vanessa    NaN    NaN  124.0    NaN

In [370]:
df2 = df.pivot_table(values = 'Revenue', index = ['Company'], columns = ['Person'])
df2

Person     Amy  Carl  Charlie    Sam  Sarah  Vanessa
Company                                             
FB         NaN  80.0      NaN    NaN  200.0      NaN
GOOG       NaN   NaN     50.0  100.0    NaN      NaN
MSFT     200.0   NaN      NaN    NaN    NaN    100.0

In [371]:
df2.isnull()

Person     Amy   Carl  Charlie    Sam  Sarah  Vanessa
Company                                              
FB        True  False     True   True  False     True
GOOG      True   True    False  False   True     True
MSFT     False   True     True   True   True    False

#### 9.4 Check info(): (Entries)

In [409]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, FB to MSFT
Data columns (total 6 columns):
Amy        1 non-null float64
Carl       1 non-null float64
Charlie    1 non-null float64
Sam        1 non-null float64
Sarah      1 non-null float64
Vanessa    1 non-null float64
dtypes: float64(6)
memory usage: 168.0+ bytes


### 10. Data input & output:

In [372]:
import pandas as pd
import numpy as np

In [373]:
pwd

'C:\\Users\\Zi Wei Fan\\Udemy\\DataScience'

#### 10.1 csv Reading & writing:

In [387]:
df = pd.read_csv('example')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [390]:
copied_csv = df.to_csv('Copied_example') # A copied csv file with name of 'Copied_example' is generated under the same file path.

In [393]:
copied_csv = pd.read_csv('Copied_example')
copied_csv
'''If there is no index = False as one of the arguments, the original index will be saved as well as one new unnamed column.'''

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [394]:
df.to_csv('Copied_example', index=False) #With the index argument, the index will not be saved.
copied_csv = pd.read_csv('Copied_example')
copied_csv

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

#### 10.2 Excel reading & writing:

In [395]:
df_excel = pd.read_excel('Excel_Sample.xlsx')
df_excel

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [397]:
df_excel2 = pd.read_excel('Excel_Sample.xlsx', sheet_name='Sheet2') # Specify the sheet to read out.
df_excel2

S1  S2  S3  S4
0   3   1   2   3
1   4   5   6   7
2   8   9  31  11
3  12  13  14  45

In [398]:
df_excel2.to_excel('Excel_Sample.xlsx', sheet_name='Sheet_New') #Save the new sheet and overwrite all the sheets.

#### 10.3 HTML reading & writing:

##### https://www.fdic.gov/bank/individual/failed/banklist.html

In [399]:
html = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')

In [400]:
type(html) #The reading from HTML is list.

list

In [403]:
html

[                                             Bank Name                City  \
 0                  Washington Federal Bank for Savings             Chicago   
 1      The Farmers and Merchants State Bank of Argonia             Argonia   
 2                                  Fayette County Bank          Saint Elmo   
 3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 4                                       First NBC Bank         New Orleans   
 5                                        Proficio Bank  Cottonwood Heights   
 6                        Seaway Bank and Trust Company             Chicago   
 7                               Harvest Community Bank          Pennsville   
 8                                          Allied Bank            Mulberry   
 9                         The Woodbury Banking Company            Woodbury   
 10                              First CornerStone Bank     King of Prussia   
 11                                  Trust Company B

In [402]:
df_html = pd.DataFrame(html[0])
df_html

Bank Name                City  \
0                  Washington Federal Bank for Savings             Chicago   
1      The Farmers and Merchants State Bank of Argonia             Argonia   
2                                  Fayette County Bank          Saint Elmo   
3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
4                                       First NBC Bank         New Orleans   
5                                        Proficio Bank  Cottonwood Heights   
6                        Seaway Bank and Trust Company             Chicago   
7                               Harvest Community Bank          Pennsville   
8                                          Allied Bank            Mulberry   
9                         The Woodbury Banking Company            Woodbury   
10                              First CornerStone Bank     King of Prussia   
11                                  Trust Company Bank             Memphis   
12                          North Milwaukee State Bank           Milwaukee   
13                              Hometown National Bank            Longview   
14                                 The Bank of Georgia      Peachtree City   
15                                        Premier Bank              Denver   
16                                      Edgebrook Bank             Chicago   
17                              Doral Bank  En Espanol            San Juan   
18                   Capitol City Bank & Trust Company             Atlanta   
19                             Highland Community Bank             Chicago   
20                    First National Bank of Crestview           Crestview   
21                                  Northern Star Bank             Mankato   
22              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
23               The National Republic Bank of Chicago             Chicago   
24                                      NBRS Financial          Rising Sun   
25                               GreenChoice Bank, fsb             Chicago   
26                            Eastside Commercial Bank             Conyers   
27                              The Freedom State Bank             Freedom   
28                                         Valley Bank     Fort Lauderdale   
29                                         Valley Bank              Moline   
..                                                 ...                 ...   
525                                  ANB Financial, NA         Bentonville   
526                                          Hume Bank                Hume   
527                             Douglass National Bank         Kansas City   
528                                  Miami Valley Bank            Lakeview   
529                                            NetBank          Alpharetta   
530                          Metropolitan Savings Bank          Pittsburgh   
531                                    Bank of Ephraim             Ephraim   
532                                      Reliance Bank        White Plains   
533              Guaranty National Bank of Tallahassee         Tallahassee   
534                                Dollar Savings Bank              Newark   
535                               Pulaski Savings Bank        Philadelphia   
536              First National Bank of Blanchardville      Blanchardville   
537                              Southern Pacific Bank            Torrance   
538                        Farmers Bank of Cheneyville         Cheneyville   
539                                      Bank of Alamo               Alamo   
540             AmTrade International Bank  En Espanol             Atlanta   
541                     Universal Federal Savings Bank             Chicago   
542                       Connecticut Bank of Commerce            Stamford   
543                                   New Century Bank     Shelby Township   
544                              Net 1st National Bank          Boc

#### 10.4 SQL reading:
##### The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. 
For SQLite this is included in Python’s standard library by default. 

In [404]:
from sqlalchemy import create_engine

In [405]:
engine = create_engine('sqlite:///:memory:')
sdf.to_sql('table_df_html', engine)
'''Add "engine" to be the connector.'''

In [408]:
sqldf = pd.read_sql('table_df_html', con=engine)
sqldf

index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

In [ ]:
### 11. 